export const categoryIconMap: Record<string, string> = {
  Health: 'favorite',
  Finance: 'account-balance-wallet',
  Career: 'work',
  Learning: 'school',
  Relationships: 'favorite-border',
  Family: 'family-restroom',
  Home: 'home',
  Vehicle: 'directions-car',
  Pets: 'pets',
  Travel: 'travel-explore',
  Productivity: 'task-alt',
  Documents: 'description',
  Insurance: 'verified-user',
  Medical: 'local-hospital',
  'Mental Wellness': 'spa',
  'Digital Life': 'devices',
  'Emergency Preparedness': 'security',
};

export const onboardingIconMap: Record<string, string> = {
  language: 'translate',
  region: 'public',
  student: 'school',
  early_career: 'flag',
  mid_career: 'timeline',
  senior_professional: 'stars',
  business_owner: 'business-center',
  parent: 'family-restroom',
  home_owner: 'home',
  retired: 'weekend',
  partner: 'favorite',
  parents: 'people',
  children: 'child-care',
  pet_owner: 'pets',
  caregiver: 'volunteer-activism',
  investor: 'show-chart',
  motorcycle_owner: 'two-wheeler',
  car_owner: 'directions-car',
  travel_focus: 'travel-explore',
};
